Vagrant.configure(2) do |config|
  config.vm.box = "sjoeboo/centos-7-1-x86-PC1"
  config.vm.network :forwarded_port, guest: 80, host: 8888
  
  config.vm.provision "shell", inline: <<-SHELL
     #sudo yum -y update
     sudo yum install -y httpd
     sudo ln -s /vagrant /var/www/html/vagrant
     sudo systemctl stop firewalld
     sudo systemctl start httpd  
SHELL
end
