Vagrant.configure(2) do |config|
  config.vm.define "one" do |one|
    one.vm.box = "sjoeboo/centos-7-1-x86-ansible"
    one.vm.network "private_network", ip: "192.168.20.5"
    one.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define "two" do |two|
    two.vm.box = "sjoeboo/centos-7-1-x86-ansible"
    two.vm.network "private_network", ip: "192.168.20.6"
    two.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  
end
