Vagrant.configure(2) do |config|
  config.vm.box = "sjoeboo/centos-7-1-x86-ansible"
  config.vm.network :forwarded_port, guest: 80, host: 8888
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
